# Generated by Django 3.0.8 on 2020-07-08 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bse_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=1000000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DecimalField(decimal_places=1, max_digits=500)),
                ('start', models.DateField(default=datetime.date(1985, 1, 1))),
                ('end', models.DateField(default=datetime.date.today)),
                ('benchmark', models.CharField(choices=[('nifty 50', 'NIFTY 50'), ('nifty 500', 'NIFTY 500'), ('sensex', 'SENSEX')], default='NIFTY 50', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Asset')),
            ],
        ),
    ]
