# Generated by Django 3.1 on 2020-12-18 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201219_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myportfolio',
            name='username',
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='Portfolio_title',
            field=models.CharField(default='O', max_length=100),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='Portfolio_type',
            field=models.CharField(choices=[('Asset Class', 'Asset Classes'), ('Tickers', 'Tickers')], default='Tickers', max_length=50),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='benchmark',
            field=models.CharField(choices=[('NIFTY50', 'NIFTY50'), ('SENSEX', 'SENSEX')], default='SENSEX', max_length=20),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_10',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_4',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_6',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_7',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_8',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_9',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='number_of_portfolio',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_10',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_4',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_6',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_7',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_8',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_9',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyPortfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
