# Generated by Django 3.1 on 2020-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201219_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolio',
            name='Portfolio_title',
            field=models.CharField(default='portfolio x', max_length=100),
        ),
    ]
