# Generated by Django 3.1 on 2021-03-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201219_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myportfolio',
            old_name='Portfolio_title',
            new_name='portfolio_title',
        ),
    ]
