# Generated by Django 4.1 on 2024-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210303_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_11',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_12',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_13',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_14',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_15',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_16',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_17',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_18',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_19',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_20',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_21',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_22',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_23',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_24',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_25',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_26',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_27',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_28',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_29',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='buy_price_30',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_11',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_12',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_13',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_14',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_15',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_16',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_17',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_18',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_19',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_20',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_21',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_22',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_23',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_24',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_25',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_26',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_27',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_28',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_29',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='quantity_30',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_19',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_20',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_29',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='ticker_symbol_30',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myportfolio',
            name='benchmark',
            field=models.CharField(choices=[('NIFTY500', 'NIFTY500'), ('SENSEX', 'SENSEX')], default='SENSEX', max_length=20),
        ),
        migrations.AlterField(
            model_name='myportfolio',
            name='number_of_portfolio',
            field=models.IntegerField(default=30),
        ),
    ]
